export const WEBSOCKET_BACKEND_PORT = 8000;
export const WEBSOCKET_CAMERA_PATH = '/ws/camera';
export const WEBSOCKET_RECONNECT_DELAY_MS = 2000;
export const WEBSOCKET_MAX_RECONNECT_DELAY_MS = 30000;
export const WEBSOCKET_MAX_RECONNECT_ATTEMPTS = 4;
export const WEBSOCKET_KEEPALIVE_INTERVAL_MS = 15000;
